rootUrl: http://127.0.0.1:3000/test/visual
gridUrl: http://127.0.0.1:4444/wd/hub
screenshotsDir: ./test/visual/screens

system:
  plugins:
    express:
      port: 3000
    sauce: true

browsers:
  chrome:
    desiredCapabilities:
      browserName: "chrome"
      version: "54.0"

  firefox:
    desiredCapabilities:
      browserName: "firefox"
      version: "37.0"

  ie:
    desiredCapabilities:
      browserName: "internet explorer"
      version: "11.0"
