sudo: false
dist: trusty
language: node_js
node_js: stable

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  google-chrome: latest

install:
  - npm install
  - npm install -g polymer-cli@0.18.0-pre.13
  - polymer install --variants

before_script:
  - gulp lint
  - ([ "$TRAVIS_EVENT_TYPE" = "pull_request" ] || TRAVIS_BRANCH=quick/${TRAVIS_BUILD_ID} xvfb-run -s '-screen 0 1024x768x24' polymer test)

script:
  - ([ "$TRAVIS_EVENT_TYPE" = "pull_request" ] || gemini test test/visual)
  - xvfb-run -s '-screen 0 1024x768x24' wct
