sudo: false
dist: xenial
language: node_js
node_js: lts/*

addons:
  firefox: latest
  chrome: stable

script:

- if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
    npm run test:sauce && npm run test:visual;
  else
    npm run check:version &&
    npm run lint &&
    npm test;
  fi

after_success:
  - "cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | coveralls"
